#general spring properties
spring.application.name=projecteuler

#database
spring.datasource.url=jdbc:sqlite:/Users/nguyennam/dev/sources/my_project/projecteuler/chubby.sqlite
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
# #########################MYSQL################################    
# spring.datasource.url=jdbc:mysql://localhost:3306/euler?useSSL=true&serverTimezone=UTC&verifyServerCertificate=true&serverSslCert=file:/Users/nguyennam/dev/server/mysql-8.0.32-macos13-arm64/mysql-8.0.32-macos13-arm64/data/ca.pem
# spring.datasource.username=nam
# spring.datasource.password=nampassword
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

#liquibase
# Enable Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/liquibase/db.changelog-master.xml

#application specific properties
namnp.app.euler.config.problem18.dataPath=/data/problem18/input1.txt
namnp.app.euler.config.problem21.upperBound=10000
namnp.app.euler.config.problem21.resultMessage=The sum of all amicable numbers under {0} is {1}