#general spring properties
spring.application.name=projecteuler

#database
spring.datasource.url=jdbc:mysql://localhost:3306/euler?useSSL=false&serverTimezone=UTC
spring.datasource.username=nam
spring.datasource.password=nampassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none

#liquibase
# Enable Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/liquibase/db.changelog-master.xml

#application specific properties
namnp.app.euler.config.problem18.dataPath=/data/problem18/input1.txt
namnp.app.euler.config.problem21.upperBound=10000