changeLogFile=src/main/resources/db/liquibase/db.changelog-master.xml
url=jdbc:mysql://localhost:3306/euler?useSSL=true&serverTimezone=UTC&verifyServerCertificate=true&serverSslCert=file:/Users/nguyennam/dev/server/mysql-8.0.32-macos13-arm64/mysql-8.0.32-macos13-arm64/data/ca.pem
username=nam
password=nampassword
driver=com.mysql.cj.jdbc.Driver