changeLogFile=src/main/resources/db/liquibase/db.changelog-master.xml
url=jdbc:mysql://localhost:3306/euler?useSSL=false&serverTimezone=UTC
username=nam
password=nampassword
driver=com.mysql.cj.jdbc.Driver